name: docker-build
description: Build docker image
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image_name }}
    - ${{ inputs.path_to_dockerfile }}
inputs:
  image_name:
    description: Name of docker image
    required: true
  path_to_dockerfile:
    description: Path to dockerfile
    required: false
    default: Dockerfile